### ISSUE TITLE
Travis-related PRs need to be reapplied 

### ISSUE THREAD

**Issue by jimklimov** [networkupstools/nut-website#16]
Results of #12 and #13 / #14 are not seen in the codebase... like someone force-pushed to master and erased recent commits?

The code is still available in https://github.com/networkupstools/nut-website/tree/pull_404 branch BTW (up-to-date with my devel fork version). There are some merge conflicts reported ATM, to look at when we have time :-)

**Comment by clepple** [comment]
pull_404 sounds like the name of one of my temporary branches- not sure why that would have prevented me from pushing to master. I know I merged in a few commits first. I will look later today.

**Comment by clepple** [comment]
Sorry for the confusion. Apparently one of my git remotes is stuck at several months ago, and won't update. Merged as of 866cf40d.

Not sure why that would have modified the pull request branches, though.

**Comment by jimklimov** [comment]
ACK, https://travis-ci.org/networkupstools/nut-website seems good now :)

**Comment by jimklimov** [comment]
Note, I don't have clues that a PR branch was changed. Rather, it was not removed at the time of merge (if there was one, I think it was merged and closed) and so it kept the changes intended for master branch at the time, including addition of Travis CI integration.
