### ISSUE TITLE
Generate directory indexes for source archives

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut-website#19]
(is this on a branch somewhere?)

https://github.com/networkupstools/nut/issues/566

**Comment by zykh** [comment]
We already do that (e1183823 on master)... or, well, at least, it works for me.

**Comment by jimklimov** [comment]
For posterity: currently the scriptware of nut-website generates the index.html files based on the local checkout of "source" repo and publishes such indexes, but if new sources appear (e.g. `nut-2.8.0-rc1.tar.gz` recently) it is up to maintainer to copy and commit them into the resulting website repo.
