### ISSUE TITLE
HID PDC spec link broken

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut-website#20]
https://networkupstools.org/ups-protocols.html
-> https://www.usb.org/document-library/power-device-class-document-10

**Comment by clepple** [comment]
Also mentioned on nut-upsdev: https://alioth-lists.debian.net/pipermail/nut-upsdev/2018-December/007424.html

Looks like a partial website update would involve `ups-protocols.html` and the contents of the `protocols/` directory.

**Comment by jimklimov** [comment]
Currently our side points to https://www.usb.org/sites/default/files/pdcv10_0.pdf which seems to be an updated version, linked from https://www.usb.org/document-library/power-device-class-document-10 page
