### ISSUE TITLE
Updating related projects

### ISSUE THREAD

**Issue by gawindx** [networkupstools/nut-website#24]
In the list of projects, there is a reference to Winnutclient on the sourceforge site.
However, this project has not been maintained since 2015 and I personally took over the development from Github : [WinNUT-Client](https://github.com/gawindx/WinNUT-Client)
The project has evolved considerably and I am quite active in its development.

I would be grateful if you could update the corresponding projects page.

**Comment by jimklimov** [comment]
Sorry about missing this issue earlier. Project list updated now, as the NUT site migrates to a rolling-release model (without freezing for a latest official release).
