### ISSUE TITLE
2 instances of NUT (one via Ethernet and one via USB)

### ISSUE THREAD

**Issue by Briandr73** [networkupstools/nut-website#38]
Hello, 

Not so much of an issue, but more of an inquiry. I have a HP Micro Mini setup running home assistant and I connected my CyberPower UPS to it via the USB cable. I added the NUT addon and integration. All works well. Very happy with it. I do have two other UPS's in my home that have a RMCARD205 in them. I am not sure if this is even possible without the use of a small Raspberry Pi, but can I somehow have two instances of nut and one of which would connect via Ethernet. The HP Micro Mini and both RMCARD205's are on the same vlan. Any help and suggestions would be appreciated.

**Comment by jimklimov** [comment]
This is the issue tracker for web-site, following up on proper NUT issue tracker ;)
